extends Node

@warning_ignore("unused_signal")
signal start_game()
@warning_ignore("unused_signal")
signal exited_spawn()
@warning_ignore("unused_signal")
signal finish_game()
@warning_ignore("unused_signal")
signal exited_gun()
@warning_ignore("unused_signal")
signal play_again()
@warning_ignore("unused_signal")
signal choose_path(id: int)
@warning_ignore("unused_signal")
signal start_dashing()
@warning_ignore("unused_signal")
signal stopped_dashing()
@warning_ignore("unused_signal")
signal enable_sliding_doors()
@warning_ignore("unused_signal")
signal disable_sliding_doors()
